# Generated by Django 5.2.7 on 2025-12-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Входные данные для теста')),
                ('expected_output', models.TextField(help_text='Ожидаемый вывод')),
                ('is_hidden', models.BooleanField(default=False, help_text='Скрытый тест (не показывается студенту)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок выполнения тестов')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
