# Generated by Django 5.2.7 on 2025-12-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_testcase_options_remove_testcase_is_hidden_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
