# Generated by Django 5.2.7 on 2025-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AddField(
            model_name='lesson',
            name='code_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='input_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='output_description',
            field=models.TextField(blank=True),
        ),
    ]
