# Generated by Django 6.0 on 2025-12-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_order_alter_module_order_and_more'),
        ('courses', '0007_alter_lesson_options_lesson_code_template_and_more'),
    ]

    operations = [
    ]
