# Generated by Django 6.0.1 on 2026-08-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20251215_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='code_template',
            field=models.TextField(blank=True, verbose_name='Шаблон кода'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='input_description',
            field=models.TextField(blank=True, verbose_name='Входные данные'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('task', 'Задача')], default='text', max_length=20, verbose_name='Тип урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок выполнения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='output_description',
            field=models.TextField(blank=True, verbose_name='Выходные данные'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
